version: '3'

services:    
  db:
    image: postgres:latest
    container_name: db
    restart: always
    tty: true
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=auchan_db
    ports:
      - "5433:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    container_name: backend
    build:
      context: ./backend
    ports:
      - "5001:5001"
    environment:
      NODE_ENV: development
      PORT: 5001
      DB_NAME: auchan_db
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      secretKey: VDlMv02KLtKEtaFBCM4G2w3OFYU72fG2
    entrypoint: ["./wait-for-it.sh", "db", "5432", "npm", "start"]
    depends_on:
      - db

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - "3000:3000"